DefaultContentLanguage = "es"

baseURL = "https://amuravela.com"

disableKinds = ["taxonomy", "term"]

[languages]
    [languages.es]
        contentDir = "content"
        languageName = "Espa√±ol"
        languageCode = "es"
        title = "L'Amuravela - Cultura e historia de Cudillero üìú"
        description = "Web oficial del serm√≥n de L'Amuravela, fiesta de inter√©s tur√≠stico dedicada a San Pedro celebrada en la villa pixueta: Cudillero."
        weight = 1
    [languages.en]
        contentDir = "content/en"
        languageName = "English"
        languageCode = "en"
        title = "L'Amuravela"
        description = "L'Amuravela official website"
        weight = 2

[params]
    copyright = "L'Amuravela"
    themeColor = "#333"
    googleAnalytics = "G-FX79BW06FQ"

    alternatePageName = "amuravela.com"
    organizationLogo = "/logo.png"
    organizationName = "L'Amuravela"

    publisherName = "L'Amuravela"
    publisherLogo = "/logo.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60